### ISSUE TITLE
plugins cannot be loaded

### ISSUE THREAD

**Issue by Enrice** [jfrog/artifactory-user-plugins#324]
Hi.

I may have a configuration problem.
I wanted to deploy 2 plugins but get the following:

```
2020-04-07 19:16:00,979 [art-init] [INFO ] (o.a.a.p.GroovyRunnerImpl:301) - Loading script from 'artifactCleanup.groovy'.
2020-04-07 19:16:01,308 [art-init] [INFO ] (o.a.a.p.e.ExecutePluginImpl:189) - Groovy execution 'cleanup' has been successfully registered.
2020-04-07 19:16:01,310 [art-init] [INFO ] (o.a.a.p.e.ExecutePluginImpl:189) - Groovy execution 'cleanupCtl' has been successfully registered.
2020-04-07 19:16:01,455 [art-init] [ERROR] (o.a.a.p.GroovyRunnerImpl:349) - Error loading script from '/var/opt/jfrog/artifactory/etc/plugins/artifactCleanup.groovy'.
groovy.lang.MissingMethodException: No signature of method: groovy.lang.Reference.scheduledCleanup_0 30 4 ? * 0() is applicable for argument types: (java.util.LinkedHashMap, artifactCleanup$_run_closure3$_closure11$_closure12) values: [[cron:0 30 4 ? * 0, delegate:org.artifactory.addon.plugin.ScriptDelegate@50418971, ...], ...]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:71)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:108)
	at artifactCleanup$_run_closure3$_closure11.doCall(artifactCleanup.groovy:142)
	at artifactCleanup$_run_closure3$_closure11.doCall(artifactCleanup.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:420)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.artifactory.addon.plugin.ScriptDelegate.jobs(ScriptDelegate.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:935)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:926)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.invokeMethod(DefaultGroovyMethods.java:980)
	at org.codehaus.groovy.runtime.dgm$353.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at Script1$_run_closure1.doCall(Script1.groovy:1)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:84)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:951)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1227)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.Script.invokeMethod(Script.java:80)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:398)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at artifactCleanup$_run_closure3.doCall(artifactCleanup.groovy:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:420)
	at groovy.lang.Closure.call(Closure.java:436)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
	at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at artifactCleanup.run(artifactCleanup.groovy:132)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.loadScript(GroovyRunnerImpl.java:342)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.getScripts(GroovyRunnerImpl.java:302)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.reloadScripts(GroovyRunnerImpl.java:126)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.init(GroovyRunnerImpl.java:145)
	at jdk.internal.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.artifactory.storage.fs.lock.aop.LockingAdvice.invoke(LockingAdvice.java:76)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy263.init(Unknown Source)
	at org.artifactory.spring.ArtifactoryApplicationContext.refresh(ArtifactoryApplicationContext.java:273)
	at org.artifactory.spring.ArtifactoryApplicationContext.<init>(ArtifactoryApplicationContext.java:153)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener.configure(ArtifactoryContextConfigListener.java:211)
	at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener.access$200(ArtifactoryContextConfigListener.java:67)
	at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener$1.run(ArtifactoryContextConfigListener.java:92)
2020-04-07 19:16:01,464 [art-init] [INFO ] (o.a.a.p.GroovyRunnerImpl:301) - Loading script from 'deleteEmptyDirs.groovy'.
2020-04-07 19:16:01,529 [art-init] [INFO ] (o.a.a.p.e.ExecutePluginImpl:189) - Groovy execution 'deleteEmptyDirsPlugin' has been successfully registered.
2020-04-07 19:16:01,627 [art-init] [ERROR] (o.a.a.p.GroovyRunnerImpl:349) - Error loading script from '/var/opt/jfrog/artifactory/etc/plugins/deleteEmptyDirs.groovy'.
groovy.lang.MissingMethodException: No signature of method: groovy.lang.Reference.scheduledDeleteEmptyDirs_0 0 5 ? * 0() is applicable for argument types: (java.util.LinkedHashMap, deleteEmptyDirs$_run_closure2$_closure6$_closure7) values: [[cron:0 0 5 ? * 0, delegate:org.artifactory.addon.plugin.ScriptDelegate@50418971, ...], ...]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:71)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:108)
	at deleteEmptyDirs$_run_closure2$_closure6.doCall(deleteEmptyDirs.groovy:57)
	at deleteEmptyDirs$_run_closure2$_closure6.doCall(deleteEmptyDirs.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:420)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.artifactory.addon.plugin.ScriptDelegate.jobs(ScriptDelegate.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:935)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:926)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.invokeMethod(DefaultGroovyMethods.java:980)
	at org.codehaus.groovy.runtime.dgm$353.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at Script1$_run_closure1.doCall(Script1.groovy:1)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:84)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:951)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1227)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.Script.invokeMethod(Script.java:80)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:398)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at deleteEmptyDirs$_run_closure2.doCall(deleteEmptyDirs.groovy:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:420)
	at groovy.lang.Closure.call(Closure.java:436)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
	at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at deleteEmptyDirs.run(deleteEmptyDirs.groovy:52)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.loadScript(GroovyRunnerImpl.java:342)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.getScripts(GroovyRunnerImpl.java:302)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.reloadScripts(GroovyRunnerImpl.java:126)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.init(GroovyRunnerImpl.java:145)
	at jdk.internal.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.artifactory.storage.fs.lock.aop.LockingAdvice.invoke(LockingAdvice.java:76)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy263.init(Unknown Source)
	at org.artifactory.spring.ArtifactoryApplicationContext.refresh(ArtifactoryApplicationContext.java:273)
	at org.artifactory.spring.ArtifactoryApplicationContext.<init>(ArtifactoryApplicationContext.java:153)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener.configure(ArtifactoryContextConfigListener.java:211)
	at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener.access$200(ArtifactoryContextConfigListener.java:67)
	at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener$1.run(ArtifactoryContextConfigListener.java:92)
2020-04-07 19:16:01,633 [art-init] [INFO ] (o.a.a.p.GroovyRunnerImpl:155) - 
==================Plugins Status===================
#  artifactCleanup.groovy               -->  Error
#  deleteEmptyDirs.groovy               -->  Error
===================================================
```

Any idea, what may have happened here?
BTW I use artifactory pro 6.17.0

Erich.

**Comment by Enrice** [comment]
Anyone?

**Comment by boris-ait** [comment]
I think it's because of day of week. You put 0. However, valid values 1-7. Put 1 if you meant Sunday.
http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html

Unfortunately, you can't understand that from the exception that you are getting. I also got such errors.
I think need to add some validation to cron expression in the plugin or in 'Jobs' closer of Artifactory.

**Comment by ilvidel** [comment]
I think I'm facing the same issue, but my cron is valid.
@Enrice did you manage to solve it?

I am getting: 
```
2020-08-03 11:48:57,083 [art-groovy-plugins-reloader] [INFO ] (o.a.a.p.GroovyRunnerImpl:249) - Script 'artifactCleanup.groovy' has changed. Reloading all scripts
2020-08-03 11:48:57,134 [art-groovy-plugins-reloader] [INFO ] (o.a.a.p.GroovyRunnerImpl:301) - Loading script from 'artifactCleanup.groovy'.
2020-08-03 11:48:57,278 [art-groovy-plugins-reloader] [INFO ] (o.a.a.p.e.ExecutePluginImpl:189) - Groovy execution 'cleanup' has been successfully registered.
2020-08-03 11:48:57,280 [art-groovy-plugins-reloader] [INFO ] (o.a.a.p.e.ExecutePluginImpl:189) - Groovy execution 'cleanupCtl' has been successfully registered.
2020-08-03 11:48:57,281 [art-groovy-plugins-reloader] [INFO ] (artifactCleanup     :-2) - Schedule job policy list: [[cron:*/10 * * * *, disablePropertiesSupport:false, dryRun:true, paceTimeMS:500, repos:[scratch-repo], timeInterval:3, timeUnit:day]]
2020-08-03 11:48:57,288 [art-groovy-plugins-reloader] [ERROR] (o.a.a.p.GroovyRunnerImpl:349) - Error loading script from '/opt/jfrog/artifactory/etc/plugins/artifactCleanup.groovy'.
groovy.lang.MissingMethodException: No signature of method: groovy.lang.Reference.scheduledCleanup_1() is applicable for argument types: (java.util.LinkedHashMap, artifactCleanup$_run_closure2$_closure7$_closure8) values: [[cron:*/10 * * * *, delegate:org.artifactory.addon.plugin.ScriptDelegate@3c53dd0d, ...], ...]
```

My json file is: 
```json
{
    "policies": [
        {
            "cron": "*/10 * * * *",
            "repos": [
                "scratch-repo"
            ],
            "timeUnit": "day",
            "timeInterval": 3,
            "dryRun": true,
            "paceTimeMS": 500,
            "disablePropertiesSupport": false
        }
    ]
}
```

**Comment by Enrice** [comment]
@ilvidel It was actually the bad cron in my case. fixed it - works now.

**Comment by DarthFennec** [comment]
@ilvidel Your cron expression is actually incorrect. Artifactory uses [quartz expressions](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html), not standard cron.

Try something like `0/10 * * * * ?` instead

**Comment by ilvidel** [comment]
@DarthFennec Thanks, I didn't know they were special cron expressions. However, I think it still doesn't work. I want it to run every day at 23:30, so I used `0 30 23 * * *` and still got the same error:
```
2020-08-04 10:27:30,861 [art-groovy-plugins-reloader] [INFO ] (artifactCleanup     :-2) - Schedule job policy list: [[cron:0 30 23 * * *, disablePropertiesSupport:false, dryRun:true, paceTimeMS:500, repos:[scratch-repo], timeInterval:6, timeUnit:months]]
2020-08-04 10:27:30,876 [art-groovy-plugins-reloader] [ERROR] (o.a.a.p.GroovyRunnerImpl:349) - Error loading script from '/opt/jfrog/artifactory/etc/plugins/artifactCleanup.groovy'.
groovy.lang.MissingMethodException: No signature of method: groovy.lang.Reference.scheduledCleanup_1() is applicable for argument types: (java.util.LinkedHashMap, artifactCleanup$_run_closure2$_closure7$_closure8) values: [[cron:0 30 23 * * *, delegate:org.artifactory.addon.plugin.ScriptDelegate@4f128b9c, ...], ...]
```

**Comment by DarthFennec** [comment]
@ilvidel Try `0 30 23 * * ?`. It doesn't explicitly say this in the documentation, but it seems like you're required to use `?` for either the day of month or day of week field.

**Comment by ilvidel** [comment]
@DarthFennec That did the trick. Thaks a lot, it was driving me nuts!
