### ISSUE TITLE
uniqueNugetDeploy throws error for artifactory 7.15.3

### ISSUE THREAD

**Issue by dakimaz** [jfrog/artifactory-user-plugins#372]
When updating from Artifactory 6.23 to 7.15 uniqueNugetDeploy stopped working. Porting the changes from this repo didn't resolve the issue and the plugin throws the following error:

```
Caused by: java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor438.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.executePluginAction(GroovyRunnerImpl.java:380)
	... 130 common frames omitted
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.jfrog.repomd.nuget.rest.handler.NuGetLocalRepoHandler(org.artifactory.addon.nuget.repomd.NuGetArtifactoryService, FakeUriInfo, null)
```

It looks like the constructor of NugetLocalRepoHandler has changed, but this documentation is not publically available.

**Comment by dakimaz** [comment]
Just tested on version 7.12.8. The plugin doesn't work here either.
Also we had to add
`@Grab(group='com.sun.jersey', module='jersey-core', version='1.19.4')` 
to the top of the file otherwise this didn't work:
`import com.sun.jersey.core.util.MultivaluedMapImpl`

**Comment by harendrar8095** [comment]
Thanks for reaching out!

This plugin is deprecated and is no longer supported. As part of our ongoing plugin [deprecation plan](https://jfrog.com/help/r/jfrog-release-information/artifactory-deprecations), we encourage you to adopt the new approach for extending Artifactory functionality using JFrog Workers.

We’re closing this for now, but feel free to reopen it if you have further questions!
