### ISSUE TITLE
synchronizeLdapGroups: plugin throws error and login fails

### ISSUE THREAD

**Issue by ib-ak** [jfrog/artifactory-user-plugins#409]
running it on kubernetes

below is my pod logs.
any suggestions?

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.artifactory.security.ldap.NewSpringSecurityLdapTemplate (file:/opt/jfrog/artifactory/app/artifactory/tomcat/webapps/artifactory/WEB-INF/lib/artifactory-core-7.35.2.jar) to field com.sun.jndi.ldap.AbstractLdapNamingEnumeration.entries
WARNING: Please consider reporting this to the maintainers of org.artifactory.security.ldap.NewSpringSecurityLdapTemplate
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-03-10T13:16:23.042Z [1;37m[jfmc ][0;39m [34m[INFO ][0;39m [744876a8b3f19c1b] [o.j.m.s.AccessTokenFilter:59  ] [http-nio-8080-exec-4] - Authentication failed: Access Token is not valid
2022-03-10T13:16:32.310Z [1;37m[jfmc ][0;39m [34m[INFO ][0;39m [294b1f020e3f7b49] [o.j.m.s.AccessTokenFilter:59  ] [http-nio-8080-exec-8] - Authentication failed: Access Token is not valid
2022-03-10T13:16:40.060Z [1;37m[jfmc ][0;39m [34m[INFO ][0;39m [7c778bd00950ac7e] [o.j.m.s.AccessTokenFilter:59  ] [http-nio-8080-exec-3] - Authentication failed: Access Token is not valid
2022-03-10T13:16:40.446Z [1;37m[jfmc ][0;39m [34m[INFO ][0;39m [ac87b4ebf9275b4 ] [o.j.m.s.AccessTokenFilter:59  ] [http-nio-8080-exec-4] - Authentication failed: Access Token is not valid
2022-03-10T13:16:41.726Z [1;37m[jfmc ][0;39m [34m[INFO ][0;39m [4304a65ab50d09e4] [o.j.m.s.AccessTokenFilter:59  ] [http-nio-8080-exec-5] - Authentication failed: Access Token is not valid
2022-03-10T13:16:49.620Z [37m[jffe ][39m [31m[1m[ERROR][22m[39m [2e7ef4754225b0b4] [                              ] [main                ] - Error: Logged in 'abhinav' is not an admin.
    at Object.callErrorFromStatus (/opt/jfrog/artifactory/app/frontend/bin/server/dist/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/opt/jfrog/artifactory/app/frontend/bin/server/dist/node_modules/@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/opt/jfrog/artifactory/app/frontend/bin/server/dist/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/opt/jfrog/artifactory/app/frontend/bin/server/dist/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at process.nextTick (/opt/jfrog/artifactory/app/frontend/bin/server/dist/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24)
    at process._tickCallback (internal/process/next_tick.js:61:11)
2022-03-10T13:16:49.890Z [1;37m[jfmc ][0;39m [34m[INFO ][0;39m [28cafa0ed4a18333] [o.j.m.s.AccessTokenFilter:59  ] [ttp-nio-8080-exec-10] - Authentication failed: Access Token is not valid
2022-03-10T13:16:49.894Z [37m[jffe ][39m [31m[1m[ERROR][22m[39m [28cafa0ed4a18333] [                              ] [main                ] - Error: Request failed with status code 401
    at createError (/opt/jfrog/artifactory/app/frontend/bin/server/dist/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/jfrog/artifactory/app/frontend/bin/server/dist/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/jfrog/artifactory/app/frontend/bin/server/dist/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2022-03-10T13:16:50.523Z [1;37m[jfmc ][0;39m [34m[INFO ][0;39m [73f80e67cd1e32dd] [o.j.m.s.AccessTokenFilter:59  ] [http-nio-8080-exec-1] - Authentication failed: Access Token is not valid
```

**Comment by nehamjfrog** [comment]
This synchronizeLdapGroups plugin is deprecated and incompatible with the most recent Artifactory versions. Please view the deprecation notice [here](https://jfrog.com/help/r/jfrog-release-information/artifactory-deprecations)
