### ISSUE TITLE
Groovy error on "repoQuota.groovy" 

### ISSUE THREAD

**Issue by Prabhakar-cg** [jfrog/artifactory-user-plugins#412]
Hi there,

I am using Artifactory 7.33.12 enterprise edition, recently i found this repoquota.groovy file for enforcing quota limit per repo but when i implement this groovy i am getting the following error

'E:\jfrog\artifactory-pro-7.33.12\var\etc\artifactory\plugins\repoQuota.groovy'.
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/E:/jfrog/artifactory-pro-7.33.12/var/etc/artifactory/plugins/repoQuota.groovy: 7: unexpected token: < @ line 7, column 1.
   <!DOCTYPE html>
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:151)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:121)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:133)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:325)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:224)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:192)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:226)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:201)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:965)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:642)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:618)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:595)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:401)
	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:341)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:338)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:336)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:242)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:229)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:320)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:262)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:545)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.loadScript(GroovyRunnerImpl.java:339)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.getScripts(GroovyRunnerImpl.java:316)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.reloadScripts(GroovyRunnerImpl.java:140)
	at org.artifactory.addon.plugin.GroovyRunnerImpl.init(GroovyRunnerImpl.java:159)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.artifactory.storage.fs.lock.aop.LockingAdvice.invoke(LockingAdvice.java:76)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy321.init(Unknown Source)
	at org.artifactory.spring.ArtifactoryApplicationContext.initReloadableBeans(ArtifactoryApplicationContext.java:303)
	at org.artifactory.spring.ArtifactoryApplicationContext.refresh(ArtifactoryApplicationContext.java:287)
	at org.artifactory.spring.ArtifactoryApplicationContext.<init>(ArtifactoryApplicationContext.java:177)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.artifactory.lifecycle.webapp.servlet.ArtifactoryContextConfigListener.configure(ArtifactoryContextConfigListener.java:271)
	at org.artifactory.lifecycle.webapp.servlet.ArtifactoryContextConfigListener$1.run(ArtifactoryContextConfigListener.java:124)
2022-03-30T16:53:08.995Z [1;32m[jfrt ][0;39m [34m[INFO ][0;39m [e50086ca73aa45ac] [o.a.a.p.GroovyRunnerImpl:315  ] [art-init            ] - Loading script from 'RepoQuotaTest.groovy'.
2022-03-30T16:53:09.004Z [1;32m[jfrt ][0;39m [1;31m[ERROR][0;39m [e50086ca73aa45ac] [o.a.a.p.GroovyRunnerImpl:363  ] [art-init            ] - Error loading script from 'E:\jfrog\artifactory-pro-7.33.12\var\etc\artifactory\plugins\RepoQuotaTest.groovy'.
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

I could see this groovy was updated 4 years ago that means is there any tune ups required to support latest version of artifactory.

Appreciate your help

Thanks!
Prabha.

**Comment by agrasth** [comment]
Hi,
Based on the logs, it appears that you are uploading the wrong file RepoQuotaTest.groovy. Instead, you should upload the correct file from this link: [repoQuota.groovy ](https://github.com/jfrog/artifactory-user-plugins/blob/master/storage/repoQuota/repoQuota.groovy).

Please note that we are planning to deprecate plugins and transition to a more suitable alternative called workers. 
The deprecation plan is currently in action. We encourage you to try out workers for your future needs. You can find more information and documentation on workers here: [JFrog Workers Documentation ](https://jfrog.com/help/r/jfrog-platform-administration-documentation/workers).

I will be closing this issue now. If you have any further questions or need additional assistance, please feel free to re-open the issue.

Thank you for your understanding.
